"$schema" = "https://starship.rs/config-schema.json"
add_newline = true
continuation_prompt = "[.](bright-black) "

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vimcmd_symbol = "[V](bold green)"

[aws]
format = "[|](bright-black) [$symbol($profile)(\\($region\\))(\\[$duration\\])]($style) "
symbol = "îŒ½ "

[azure]
format = "[|](bright-black) [$symbol($subscription)]($style) "

[battery]
format = "[|](bright-black) [$symbol$percentage]($style) "

[buf]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "ï’ "

[bun]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î¯ "

[c]
format = "[|](bright-black) [$symbol($version(-$name))]($style) "
commands = [
    [
        "clang",
        "--version",
    ],
    [
        "gcc",
        "--version",
    ],
    [
        "cc",
        "--version",
    ],
    [
        "zig",
        "cc",
        "--version",
    ],
]
symbol = "î˜ "

[cmake]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î” "

[cmd_duration]
format = "[|](bright-black) [â± $duration]($style) "

[cobol]
format = "[|](bright-black) [$symbol($version)]($style) "

[conda]
format = "[|](bright-black) [$symbol$environment]($style) "
symbol = "ï„Œ "

[container]
format = "[|](bright-black) [$symbol \\[$name\\]]($style) "

[cpp]
format = "[|](bright-black) [$symbol($version(-$name))]($style) "
commands = [
    [
        "clang",
        "--version",
    ],
    [
        "clang++",
        "--version",
    ],
    [
        "gcc",
        "--version",
    ],
    [
        "cc",
        "--version",
    ],
    [
        "zig",
        "cc",
        "--version",
    ],
]
symbol = "î˜ "

[crystal]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î˜¯ "

[daml]
format = "[|](bright-black) [$symbol($version)]($style) "

[dart]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î˜ "

[deno]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "îŸ€ "

[direnv]
format = "[|](bright-black) [$symbol$loaded/$allowed]($style) "

[docker_context]
format = "[|](bright-black) [$symbol$context]($style) "
symbol = "ïŒˆ "

[dotnet]
format = "[|](bright-black) [$symbol($version)(ğŸ¯ $tfm)]($style) "

[elixir]
format = "[|](bright-black) [$symbol($version \\(OTP $otp_version\\))]($style) "
symbol = "î˜­ "

[elm]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î˜¬ "

[erlang]
format = "[|](bright-black) [$symbol($version)]($style) "

[fennel]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "îš¯ "

[fortran]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "îŸ "

[fossil_branch]
format = "[|](bright-black) [$symbol$branch]($style) "
symbol = "ï˜ "

[fossil_metrics]
format = "[|](bright-black) [+$added]($added_style)\\]\\[[-$deleted]($deleted_style) "

[gcloud]
format = "[|](bright-black) [$symbol$account(@$domain)(\\($region\\))]($style) "
symbol = "îŸ± "

[git_branch]
format = "[$branch]($style)"
style = "bold 7"
symbol = "ï˜ "

[git_commit]
format = "[|](bright-black) [\\($hash$tag\\)]($style) "
tag_symbol = " ï’ "

[git_metrics]
format = "[|](bright-black) [+$added]($added_style)\\]\\[[-$deleted]($deleted_style) "
disabled = true

[git_state]
format = "[|](bright-black) [$state ($progress_current/$progress_total)]($style) "

[git_status]
format = """
[$conflicted](red)\
[$deleted](red)\
[$renamed](yellow)\
[$modified](yellow)\
[$typechanged](yellow)\
[$staged](green)\
[$untracked](green)\
[$stashed](bright-black)\
[$ahead_behind](cyan)\
 """
conflicted = "c"
deleted = "x"
renamed = "r"
modified = "m"
typechanged = "t"
staged = "g"
untracked = "u"
stashed = "s"
ahead = "a"
behind = "b"
diverged = "d"

[gleam]
format = "[|](bright-black) [$symbol($version)]($style) "

[golang]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î˜§ "

[gradle]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î™  "

[guix_shell]
format = "[|](bright-black) [$symbol]($style) "
symbol = "ïŒ¥ "

[haskell]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î· "

[haxe]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î™¦ "

[helm]
format = "[|](bright-black) [$symbol($version)]($style) "

[hg_branch]
format = "[|](bright-black) [$symbol$branch]($style) "
symbol = "ï˜ "

[hostname]
format = "[|](bright-black) [$ssh_symbol($hostname)]($style) "
ssh_symbol = "î¬ "

[java]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î‰– "

[jobs]
format = "[|](bright-black) [$symbol$number]($style) "

[julia]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î˜¤ "

[kotlin]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î˜´ "

[kubernetes]
format = "[|](bright-black) [$symbol$context( \\($namespace\\))]($style) "

[localip]
format = "[|](bright-black) [$localipv4]($style) "

[lua]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î˜  "

[memory_usage]
format = "[|](bright-black) $symbol[$ram( | $swap)]($style) "
symbol = "ó°› "

[meson]
format = "[|](bright-black) [$symbol$project]($style) "
symbol = "ó°”· "

[mise]
format = "[|](bright-black) [$symbol$health]($style) "

[mojo]
format = "[|](bright-black) [$symbol($version)]($style) "

[nats]
format = "[|](bright-black) [$symbol$name]($style) "

[netns]
format = "[|](bright-black) [$symbol \\[$name\\]]($style) "

[nim]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "ó°†¥ "

[nix_shell]
format = "[|](bright-black) [$symbol$state( \\($name\\))]($style) "
symbol = "ïŒ“ "

[nodejs]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "îœ˜ "

[ocaml]
format = "[|](bright-black) [$symbol($version) (\\($switch_indicator$switch_name\\))]($style) "
symbol = "î™º "

[odin]
format = "[|](bright-black) [$symbol($version )]($style) "

[opa]
format = "[|](bright-black) [$symbol($version)]($style) "

[openstack]
format = "[|](bright-black) [$symbol$cloud(\\($project\\))]($style) "

[os]
format = "[|](bright-black) [$symbol]($style) "
disabled = true

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
AOSC = "ïŒ "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[package]
format = "[|](bright-black) [$symbol$version]($style) "
symbol = "ó°— "

[perl]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î™¾ "

[php]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î˜ˆ "

[pijul_channel]
format = "[|](bright-black) [$symbol$channel]($style) "
symbol = "ï˜ "

[pixi]
format = "[|](bright-black) [$symbol$version( $environment)]($style) "
symbol = "ó°— "

[pulumi]
format = "[|](bright-black) [$symbol$stack]($style) "

[purescript]
format = "[|](bright-black) [$symbol($version)]($style) "

[python]
format = "[|](bright-black) [${symbol}${pyenv_prefix}(${version})(\\($virtualenv\\))]($style) "
style = "bold blue"
symbol = "îˆµ "

[quarto]
format = "[|](bright-black) [$symbol($version)]($style) "

[raku]
format = "[|](bright-black) [$symbol($version-$vm_version)]($style) "

[red]
format = "[|](bright-black) [$symbol($version)]($style) "

[rlang]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "ó°Ÿ” "

[ruby]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î‘ "

[rust]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "ó±˜— "

[scala]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "îœ· "

[shell]
style = "cyan bold"
bash_indicator = "b"
zsh_indicator = "z"
fish_indicator = "ó°ˆº "
powershell_indicator = "ï‘ _"
cmd_indicator = "c"
unknown_indicator = "mystery shell"

[singularity]
format = "[|](bright-black) [$symbol\\[$env\\]]($style) "

[solidity]
format = "[|](bright-black) [$symbol($version)]($style) "

[spack]
format = "[|](bright-black) [$symbol$environment]($style) "

[status]
format = "[|](bright-black) [$symbol$status]($style) "
symbol = "ï‘§ "

[sudo]
format = "[|](bright-black) [as $symbol]($style) "

[swift]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î• "

[terraform]
format = "[|](bright-black) [$symbol$workspace]($style) "

[time]
format = "[|](bright-black) [$time]($style) "

[typst]
format = "[|](bright-black) [$symbol($version)]($style) "

[username]
format = "[|](bright-black) [$user]($style) "

[vagrant]
format = "[|](bright-black) [$symbol($version)]($style) "

[vcsh]
format = "[|](bright-black) vcsh [$symbol$repo]($style) "

[vlang]
format = "[|](bright-black) [$symbol($version)]($style) "

[xmake]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "î” "

[zig]
format = "[|](bright-black) [$symbol($version)]($style) "
symbol = "îš© "

[directory]
read_only = " ó°Œ¾"
